server:
  port: 8205
spring:
  application:
    name: minimall-cart-service
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cart_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  knife4j:
    enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
