CREATE TABLE IF NOT EXISTS t_stock (
  id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  available BIGINT DEFAULT 0,
  reserved BIGINT DEFAULT 0,
  alert_threshold BIGINT DEFAULT 10,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sku (sku_id)
);

CREATE TABLE IF NOT EXISTS t_stock_journal (
  id BIGINT NOT NULL AUTO_INCREMENT,
  sku_id BIGINT NOT NULL,
  quantity BIGINT NOT NULL,
  type TINYINT NOT NULL,
  reason VARCHAR(255),
  order_no VARCHAR(32),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS t_stock_transfer (
  id BIGINT NOT NULL,
  from_sku_id BIGINT NOT NULL,
  to_sku_id BIGINT NOT NULL,
  quantity BIGINT NOT NULL,
  reason VARCHAR(256),
  operator_id BIGINT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS t_stock_count_task (
  id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  expected_quantity BIGINT NOT NULL,
  actual_quantity BIGINT,
  diff_quantity BIGINT,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(256),
  operator_id BIGINT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id)
);
