CREATE TABLE IF NOT EXISTS t_stock (
  id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  available BIGINT DEFAULT 0,
  reserved BIGINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sku (sku_id)
);