CREATE TABLE IF NOT EXISTS t_sku (
  id BIGINT NOT NULL,
  spu_id BIGINT NOT NULL,
  sku_name VARCHAR(128) NOT NULL,
  price DECIMAL(12,2) DEFAULT 0,
  stock INT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id)
);