CREATE TABLE IF NOT EXISTS t_pay_record (
  id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  amount DECIMAL(12,2) DEFAULT 0,
  status VARCHAR(32) DEFAULT 'PENDING',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  INDEX idx_order (order_id)
);