server:
  port: 8080
spring:
  application:
    name: minimall-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0

minimall:
  jwt:
    secret: dev-secret-change-me-32bytes-min!!