server:
  port: 8203
spring:
  application:
    name: minimall-merchant-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/merchant_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root