CREATE TABLE IF NOT EXISTS t_merch_shop (
  id BIGINT NOT NULL,
  shop_name VARCHAR(128) NOT NULL,
  license_no VARCHAR(64),
  status VARCHAR(32) DEFAULT 'PENDING',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);